source 'https://rubygems.org'

gem 'rails', '4.2.6'
gem 'rails-api'
gem 'pg'
gem 'active_model_serializers', github: 'rails-api/active_model_serializers'
gem 'decent_exposure'
gem 'rack-cors', require: 'rack/cors'
gem 'bcrypt'
gem 'jwt'

group :development, :test do
  gem 'pry'
  gem 'spring'
  gem 'rubocop'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'rspec-collection_matchers'
  gem 'factory_girl_rails'
  gem 'database_cleaner'
end
