source 'https://rubygems.org'

gem 'rails', '4.2.5'
gem 'rails-api'
gem 'pg'
gem 'active_model_serializers', github: 'rails-api/active_model_serializers'
gem 'decent_exposure'
gem 'rack-cors', require: 'rack/cors'

group :development, :test do
  gem 'pry'
  gem 'spring'
  gem 'rubocop'
end
